CREATE TABLE "MYNOTES" 
(	
   "ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 4 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
   "NOTES" VARCHAR2(4000 CHAR),  
   CONSTRAINT "MYNOTES_ID_PK" PRIMARY KEY ("ID")
   USING INDEX  ENABLE
) ;


INSERT INTO MYNOTES (notes) VALUES ('Travel to Kashmir was an unforgettable experience with stunning landscapes.');
INSERT INTO MYNOTES (notes) VALUES ('Hotel Booking in Delhi was confirmed for the weekend.'); 
INSERT INTO MYNOTES (notes) VALUES ('Arrived in Paris, the Eiffel Tower was breathtaking at sunset.');
INSERT INTO MYNOTES (notes) VALUES ('Loved the croissants at a tiny bakery near the Seine.');
INSERT INTO MYNOTES (notes) VALUES ('Tokyo streets are incredibly clean and efficient.');
INSERT INTO MYNOTES (notes) VALUES ('Central Park was a perfect escape from the city buzz.');
INSERT INTO MYNOTES (notes) VALUES ('Bangkok night markets are a must‑try for street food.');
INSERT INTO MYNOTES (notes) VALUES ('Sydney Opera House illuminated at night is unforgettable.');
INSERT INTO MYNOTES (notes) VALUES ('Rome’s ancient ruins are best explored with a guide.');
INSERT INTO MYNOTES (notes) VALUES ('Tapas in Barcelona were small but packed with flavor.');
INSERT INTO MYNOTES (notes) VALUES ('Dubai’s desert safari was an exhilarating experience.');
INSERT INTO MYNOTES (notes) VALUES ('Cape Town’s Table Mountain offered stunning panoramic views.'); 
INSERT INTO MYNOTES (notes) VALUES ('Patient tolerated surgery well; margins clear.'); 
INSERT INTO MYNOTES (notes) VALUES ('Started on pembrolizumab - mild fatigue reported.'); 
INSERT INTO MYNOTES (notes) VALUES ('Completed 6 cycles of FOLFOX; CEA levels decreasing.'); 
INSERT INTO MYNOTES (notes) VALUES ('Androgen deprivation therapy initiated; PSA dropped to 0.8 ng/mL.'); 
INSERT INTO MYNOTES (notes) VALUES ('Bilateral lung metastases stable after 8 cycles of nivolumab.'); 
INSERT INTO MYNOTES (notes) VALUES ('CR achieved after induction; proceeding to consolidation.'); 
INSERT INTO MYNOTES (notes) VALUES ('Started on gemcitabine + nab‑paclitaxel; mild neutropenia noted.'); 
INSERT INTO MYNOTES (notes) VALUES ('Debulking surgery successful; plan for platinum‑based chemo.'); 
INSERT INTO MYNOTES (notes) VALUES ('PET scan shows complete metabolic response after 4 cycles of ABVD.'); 
INSERT INTO MYNOTES (notes) VALUES ('Total thyroidectomy performed; awaiting radioactive iodine.');
INSERT INTO MYNOTES (notes) VALUES ('Breast cancer screening scheduled for next month.');
INSERT INTO MYNOTES (notes) VALUES ('Lung cancer screening scheduled for next month.');